openapi: 3.1.0
x-stoplight:
  id: dsrp4ol3j3ihk
info:
  title: i-Match API
  version: '1.0'
  summary: i-Match のAPI
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: user一覧
      tags:
        - index
      responses:
        '200':
          description: HTTP_OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: get-users
    post:
      summary: user作成
      tags:
        - index
      responses: {}
      operationId: post-users
components:
  schemas:
    User:
      type: object
      x-examples:
        example-1:
          id: 1
          class: SD3D
          name: 翔
          email: 2001195@asojuku.ac.jp
          password: Aso-2001195
          created_at: '2022-06-29 10:29:50'
          updated_at: '2022-06-29 10:29:50'
          deleted_at: '2022-06-29 10:29:50'
      examples: []
      properties:
        id:
          type: integer
          example: 1
          format: int64
          minimum: 1
          maximum: 255
        class:
          type: string
          example: SD3D
          maxLength: 30
          minLength: 1
          pattern: '^[A-Z]{2}[0-9][A-Z]'
        name:
          type: string
          example: 翔
          maxLength: 30
          minLength: 1
        email:
          type: string
          description: 学校用メールアドレス
          example: 2001195@s.asojuku.ac.jp
          format: email
          minLength: 23
          maxLength: 23
          pattern: '^[0-9]{7}@s\.asojuku\.ac\.jp'
        created_at:
          type: string
          format: date-time
          example: '2022-06-29 10:29:50'
        updated_at:
          type: string
          format: date-time
          example: '2022-06-29 10:29:50'
        deleted_at:
          type: string
          example: '2022-06-29 10:29:50'
          format: date-time
      required:
        - class
        - name
        - email
      description: ユーザーModel
