openapi: 3.1.0
x-stoplight:
  id: dsrp4ol3j3ihk
info:
  title: i-Match API
  version: '1.0'
  summary: i-Match のAPI
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: user一覧
      tags:
        - index
      responses:
        '200':
          description: HTTP_OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: get-users
    post:
      summary: user作成
      tags:
        - index
      responses: {}
      operationId: post-users
  /uaerSkill:
    get:
      summary: index
      tags:
        - EndPoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSkill'
      operationId: get-uaerTest
    post:
      summary: store
      tags:
        - EndPoint
      responses: {}
      operationId: post-uaerTest
    parameters: []
  /SkillCategories:
    get:
      summary: SkillCategories一覧
      tags:
        - Endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SkillCategories'
              examples: {}
      operationId: get-SkillCategories
    post:
      summary: create
      tags:
        - Endpoint
      responses: {}
      operationId: post-SkillCategories
components:
  schemas:
    User:
      type: object
      x-examples:
        example-1:
          id: 1
          class: SD3D
          name: 翔
          email: 2001195@asojuku.ac.jp
          password: Aso-2001195
          created_at: '2022-06-29 10:29:50'
          updated_at: '2022-06-29 10:29:50'
          deleted_at: '2022-06-29 10:29:50'
      examples: []
      properties:
        id:
          type: integer
          example: 1
          format: int64
          minimum: 1
          maximum: 255
        class:
          type: string
          example: SD3D
          maxLength: 30
          minLength: 1
          pattern: '^[A-Z]{2}[0-9][A-Z]'
        name:
          type: string
          example: 翔
          maxLength: 30
          minLength: 1
        email:
          type: string
          description: 学校用メールアドレス
          example: 2001195@s.asojuku.ac.jp
          format: email
          minLength: 23
          maxLength: 23
          pattern: '^[0-9]{7}@s\.asojuku\.ac\.jp'
        created_at:
          type: string
          format: date-time
          example: '2022-06-29 10:29:50'
        updated_at:
          type: string
          format: date-time
          example: '2022-06-29 10:29:50'
        deleted_at:
          type: string
          example: '2022-06-29 10:29:50'
          format: date-time
      required:
        - class
        - name
        - email
      description: ユーザーModel
      title: ''
    UserSkill:
      type: object
      x-examples:
        example-1:
          id: 1
          user_id: 1
          skill_id: 1
          practical_flag: true
          learning_flag: true
          level: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      x-tags:
        - Model
        - Users
        - Skill
      description: ''
      title: ''
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        skill_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        practical_flag:
          type: boolean
        learning_flag:
          type: boolean
        level:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
          example: 1
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    SkillCategories:
      type: object
      x-examples:
        example-1:
          id: 1
          name: name
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Skills:
      type: object
      x-examples:
        example-1:
          id: 1
          category_id: 1
          name: name
          depth: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        category_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        depth:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    SkillRelations:
      type: object
      x-examples:
        example-1:
          id: 1
          primary_skill_id: 1
          secondary_skill_id: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        primary_skill_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        secondary_skill_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Recruits:
      type: object
      x-examples:
        example-1:
          id: 1
          user_id: 1
          title: name
          contents: name
          purpose_id: 1
          persons: 1
          due: '2022-01-01 11:11:11'
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        title:
          type: string
        contents:
          type: string
        purpose_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        persons:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        due:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    RecruitSkill:
      type: object
      x-examples:
        example-1:
          id: 1
          recruit_id: 1
          skill_id: 1
          level: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        recruit_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        skill_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        level:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    RecruitUser:
      type: object
      x-examples:
        example-1:
          id: 1
          recruit_id: 1
          user_id: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        recruit_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    RecruitPurPoses:
      type: object
      x-examples:
        example-1:
          id: 1
          name: name
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Rooms:
      type: object
      x-examples:
        example-1:
          id: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    RoomUser:
      type: object
      x-examples:
        example-1:
          id: 1
          room_id: 1
          user_id: 1
          name: name
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        room_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Chats:
      type: object
      x-examples:
        example-1:
          id: 1
          room_id: 1
          user_id: 1
          message: name
          read: true
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          example: 255
        room_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        message:
          type: string
        read:
          type: boolean
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Informations:
      type: object
      x-examples:
        example-1:
          id: 1
          user_id: 1
          title: string
          contents: string
          read: true
          category_id: 1
          url: string
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        title:
          type: string
        contents:
          type: string
        read:
          type: boolean
        category_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        url:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
    InformationCategories:
      type: object
      x-examples:
        example-1:
          id: 1
          name: string
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    Teachers:
      type: object
      x-examples:
        example-1:
          id: 1
          name: string
          email: string
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        email:
          type: string
          pattern: '^[0-9]{7}@asojuku\.ac\.jp'
        password:
          type: string
          format: password
          minLength: 8
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        '':
          type: string
    Events:
      type: object
      x-examples:
        example-1:
          id: 1
          teacher_id: 1
          title: string
          contents: string
          due: '2022-01-01 11:11:11'
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        teacher_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        title:
          type: string
        contents:
          type: string
        due:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    SkillRequests:
      type: object
      x-examples:
        example-1:
          id: 1
          user_id: 1
          name: string
          message: string
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        user_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        name:
          type: string
        message:
          type: string
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
    SkillRequestTeacher:
      type: object
      x-examples:
        example-1:
          id: 1
          skill_request_id: 1
          skill_id: 1
          teacher_id: 1
          created_at: '2022-01-01 11:11:11'
          updated_at: '2022-01-01 11:11:11'
          deleted_at: '2022-01-01 11:11:11'
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        skill_request_id:
          type: integer
          minimum: 1
          maximum: 255
          format: int64
        skill_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        teacher_id:
          type: integer
          format: int64
          minimum: 1
          maximum: 255
        created_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        updated_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
        deleted_at:
          type: string
          format: date-time
          example: '2022-01-01 11:11:11'
